### ISSUE TITLE
chain dependency no longer exists

### ISSUE THREAD

**Issue by nimajalali** [feyeleanor/lists#1]
The dependency github.com/feyeleanor/chain no longer exists.

Any reason why?

Thanks!

**Comment by joshua** [comment]
:+1: 

See goamz/goamz#90

**Comment by feyeleanor** [comment]
I have no idea what happened to the chain repo (which I haven't worked on in years) but it's now reinstated from my local repo. I also have no idea why neither of these issues turned up in my inbox :/
